# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: envio-indexer
networks:
  - id: 31611
    rpc: https://rpc.test.mezo.org
    start_block: 8470000
    contracts:
      - name: Dapper
        address:
          - 0x7F3534743D998ef4a9894624b49CCd45Aa4fffD8
          - 0x3eE563948E28f33160969e648864E1A02a06EaE8
        handler: src/EventHandlers.ts
        events:
          - event: Initialized(address indexed depositToken, uint256 interestRateBps, address yieldVault, address beneficiaryVault)
          - event: Approval(address indexed owner, address indexed spender, uint256 value)
          - event: Deposit(address indexed sender, address indexed owner, uint256 assets, uint256 shares)
          - event: Staked(uint256 indexed stakeId, address indexed user, uint256 amountStaked, uint256 lockDuration, uint256 unlockTimestamp, uint256 interestPaid)
          - event: Transfer(address indexed from, address indexed to, uint256 value)
          - event: Unstaked(uint256 indexed stakeId, address indexed receiver, uint256 feeGenerated)
          - event: Withdraw(address indexed sender, address indexed receiver, address indexed owner, uint256 assets, uint256 shares)
          - event: InterestRateBpsSet(uint256 interestRateBps)
unordered_multichain_mode: true
preload_handlers: true
field_selection:
  transaction_fields:
    - hash
